/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-configs-recommended.ts' */

export = {
  plugins: ['@ornikar/neverthrow'],
  rules: {
    '@ornikar/neverthrow/must-use-result': 'error',
  },
};
